export { default as Home } from "./Home/Home";
export { default as Shop } from "./Shop/Shop";
export { default as Layout } from "./Layout/Layout";
export { default as About } from "./About/About";
export { default as Account } from "./Account/Account";
export { default as FAQ } from "./FAQ/FAQ";
export { default as Product } from "./Product/Product";
export { default as LoginPage } from "./Account/LoginPage";
export { default as RegisterPage } from "./Account/RegisterPage";